### ISSUE TITLE
General Confusion

### ISSUE THREAD

**Issue by elwooha6** [markolo25/Electron-Curse#2]
So I tried the app and I am a bit confused. Is this just a wrapper for the curse web client or can I actually use it to manage minecraft and wow mods? I realize there is a mods item in the menu but when I clicked it I only got a white screen with no text or images.

**Comment by markolo25** [comment]
you have this mistaken with the curse client, this is a client for the curse voice app which is like discord, skype. actually, 

EDIT: prior to writing the above i didn't know curse merged the mod client and the voice app, hmm I'll see what I can do, as when I tried getting game detection working, so I'd imagine adding game modding on top of that would be out of the scope for this project...

**Comment by elwooha6** [comment]
I see, thanks for answering.

**Comment by markolo25** [comment]
sorry...
